function stackSubjectsContrasts(rootData,glm,distType,sl)

% get analyses names from example subject
exampleInputDir = fullfile(rootData,'RDMs',glm,'sub-01','rsaContrasts',distType,sl);
cd(exampleInputDir)
tmpFname = dir('*smth*'); % find all files that were already smoothed - they are the ones to use for concatination
fname = cell(size(tmpFname));
for iAnalysis = 1:length(fname)
    fname{iAnalysis} = tmpFname(iAnalysis).name(1:end-4); % get rid of .nii suffix
end

outputDir = fullfile(rootData,'RDMs',glm,'groupStats','stackedInputs',distType,sl);
mkdir(outputDir);

for iAn = 1:length(fname)
    if strcmp(sl,'surf')
            system (['mri_concat '...
                fullfile(rootData,'RDMs',glm,'sub-01','rsaContrasts',distType,sl,[fname{iAn} '.mgh']) ' ' ...
                fullfile(rootData,'RDMs',glm,'sub-02','rsaContrasts',distType,sl,[fname{iAn} '.mgh']) ' ' ...
                fullfile(rootData,'RDMs',glm,'sub-03','rsaContrasts',distType,sl,[fname{iAn} '.mgh']) ' ' ...
                fullfile(rootData,'RDMs',glm,'sub-04','rsaContrasts',distType,sl,[fname{iAn} '.mgh']) ' ' ...
                fullfile(rootData,'RDMs',glm,'sub-05','rsaContrasts',distType,sl,[fname{iAn} '.mgh']) ' ' ...
                fullfile(rootData,'RDMs',glm,'sub-06','rsaContrasts',distType,sl,[fname{iAn} '.mgh']) ' ' ...
                fullfile(rootData,'RDMs',glm,'sub-07','rsaContrasts',distType,sl,[fname{iAn} '.mgh']) ' ' ...
                fullfile(rootData,'RDMs',glm,'sub-08','rsaContrasts',distType,sl,[fname{iAn} '.mgh']) ' ' ...
                fullfile(rootData,'RDMs',glm,'sub-09','rsaContrasts',distType,sl,[fname{iAn} '.mgh']) ' ' ...
                fullfile(rootData,'RDMs',glm,'sub-10','rsaContrasts',distType,sl,[fname{iAn} '.mgh']) ' ' ...
                fullfile(rootData,'RDMs',glm,'sub-11','rsaContrasts',distType,sl,[fname{iAn} '.mgh']) ' ' ...
                fullfile(rootData,'RDMs',glm,'sub-12','rsaContrasts',distType,sl,[fname{iAn} '.mgh']) ' ' ...
                fullfile(rootData,'RDMs',glm,'sub-13','rsaContrasts',distType,sl,[fname{iAn} '.mgh']) ' ' ...
                fullfile(rootData,'RDMs',glm,'sub-14','rsaContrasts',distType,sl,[fname{iAn} '.mgh']) ' ' ...
                fullfile(rootData,'RDMs',glm,'sub-15','rsaContrasts',distType,sl,[fname{iAn} '.mgh']) ' ' ...
                fullfile(rootData,'RDMs',glm,'sub-16','rsaContrasts',distType,sl,[fname{iAn} '.mgh']) ' ' ...
                fullfile(rootData,'RDMs',glm,'sub-17','rsaContrasts',distType,sl,[fname{iAn} '.mgh']) ' ' ...
                fullfile(rootData,'RDMs',glm,'sub-18','rsaContrasts',distType,sl,[fname{iAn} '.mgh']) ' ' ...
                fullfile(rootData,'RDMs',glm,'sub-19','rsaContrasts',distType,sl,[fname{iAn} '.mgh']) ' ' ...
                fullfile(rootData,'RDMs',glm,'sub-20','rsaContrasts',distType,sl,[fname{iAn} '.mgh']) ' ' ...
                fullfile(rootData,'RDMs',glm,'sub-21','rsaContrasts',distType,sl,[fname{iAn} '.mgh']) ' ' ...
                fullfile(rootData,'RDMs',glm,'sub-22','rsaContrasts',distType,sl,[fname{iAn} '.mgh']) ' ' ...
                fullfile(rootData,'RDMs',glm,'sub-23','rsaContrasts',distType,sl,[fname{iAn} '.mgh']) ' ' ...
                fullfile(rootData,'RDMs',glm,'sub-24','rsaContrasts',distType,sl,[fname{iAn} '.mgh']) ' ' ...
                fullfile(rootData,'RDMs',glm,'sub-25','rsaContrasts',distType,sl,[fname{iAn} '.mgh']) ' ' ...
                fullfile(rootData,'RDMs',glm,'sub-26','rsaContrasts',distType,sl,[fname{iAn} '.mgh']) ' ' ...
                fullfile(rootData,'RDMs',glm,'sub-27','rsaContrasts',distType,sl,[fname{iAn} '.mgh']) ' ' ...
                fullfile(rootData,'RDMs',glm,'sub-28','rsaContrasts',distType,sl,[fname{iAn} '.mgh']) ' ' ...
                '--o ' fullfile(outputDir,[fname{iAn} '.mgh'])]);
    else
            
            system (['fslmerge -t ' fullfile(outputDir,fname{iAn}) ' ' ...
                fullfile(rootData,'RDMs',glm,'sub-01','rsaContrasts',distType,sl,[fname{iAn} '.nii']) ' ' ...
                fullfile(rootData,'RDMs',glm,'sub-02','rsaContrasts',distType,sl,[fname{iAn} '.nii']) ' ' ...
                fullfile(rootData,'RDMs',glm,'sub-03','rsaContrasts',distType,sl,[fname{iAn} '.nii']) ' ' ...
                fullfile(rootData,'RDMs',glm,'sub-04','rsaContrasts',distType,sl,[fname{iAn} '.nii']) ' ' ...
                fullfile(rootData,'RDMs',glm,'sub-05','rsaContrasts',distType,sl,[fname{iAn} '.nii']) ' ' ...
                fullfile(rootData,'RDMs',glm,'sub-06','rsaContrasts',distType,sl,[fname{iAn} '.nii']) ' ' ...
                fullfile(rootData,'RDMs',glm,'sub-07','rsaContrasts',distType,sl,[fname{iAn} '.nii']) ' ' ...
                fullfile(rootData,'RDMs',glm,'sub-08','rsaContrasts',distType,sl,[fname{iAn} '.nii']) ' ' ...
                fullfile(rootData,'RDMs',glm,'sub-09','rsaContrasts',distType,sl,[fname{iAn} '.nii']) ' ' ...
                fullfile(rootData,'RDMs',glm,'sub-10','rsaContrasts',distType,sl,[fname{iAn} '.nii']) ' ' ...
                fullfile(rootData,'RDMs',glm,'sub-11','rsaContrasts',distType,sl,[fname{iAn} '.nii']) ' ' ...
                fullfile(rootData,'RDMs',glm,'sub-12','rsaContrasts',distType,sl,[fname{iAn} '.nii']) ' ' ...
                fullfile(rootData,'RDMs',glm,'sub-13','rsaContrasts',distType,sl,[fname{iAn} '.nii']) ' ' ...
                fullfile(rootData,'RDMs',glm,'sub-14','rsaContrasts',distType,sl,[fname{iAn} '.nii']) ' ' ...
                fullfile(rootData,'RDMs',glm,'sub-15','rsaContrasts',distType,sl,[fname{iAn} '.nii']) ' ' ...
                fullfile(rootData,'RDMs',glm,'sub-16','rsaContrasts',distType,sl,[fname{iAn} '.nii']) ' ' ...
                fullfile(rootData,'RDMs',glm,'sub-17','rsaContrasts',distType,sl,[fname{iAn} '.nii']) ' ' ...
                fullfile(rootData,'RDMs',glm,'sub-18','rsaContrasts',distType,sl,[fname{iAn} '.nii']) ' ' ...
                fullfile(rootData,'RDMs',glm,'sub-19','rsaContrasts',distType,sl,[fname{iAn} '.nii']) ' ' ...
                fullfile(rootData,'RDMs',glm,'sub-20','rsaContrasts',distType,sl,[fname{iAn} '.nii']) ' ' ...
                fullfile(rootData,'RDMs',glm,'sub-21','rsaContrasts',distType,sl,[fname{iAn} '.nii']) ' ' ...
                fullfile(rootData,'RDMs',glm,'sub-22','rsaContrasts',distType,sl,[fname{iAn} '.nii']) ' ' ...
                fullfile(rootData,'RDMs',glm,'sub-23','rsaContrasts',distType,sl,[fname{iAn} '.nii']) ' ' ...
                fullfile(rootData,'RDMs',glm,'sub-24','rsaContrasts',distType,sl,[fname{iAn} '.nii']) ' ' ...
                fullfile(rootData,'RDMs',glm,'sub-25','rsaContrasts',distType,sl,[fname{iAn} '.nii']) ' ' ...
                fullfile(rootData,'RDMs',glm,'sub-26','rsaContrasts',distType,sl,[fname{iAn} '.nii']) ' ' ...
                fullfile(rootData,'RDMs',glm,'sub-27','rsaContrasts',distType,sl,[fname{iAn} '.nii']) ' ' ...
                fullfile(rootData,'RDMs',glm,'sub-28','rsaContrasts',distType,sl,[fname{iAn} '.nii'])]);      
                
                gunzip(fullfile(outputDir,[fname{iAn} '.nii.gz']));
                delete(fullfile(outputDir,[fname{iAn} '.nii.gz']))
        
        
        
    end
    
end